apiVersion: v2
name: mongodb-chart
description: A Helm chart for deploying MongoDB in a Kubernetes cluster

# Specifies this chart is an application chart containing templates for deployment
type: application

# Versioning for the chart itself (increment with changes to chart/templates)
version: 0.1.0

# Application version (reflects the version of the MongoDB deployment)
appVersion: "4.4.0"
