apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-chart
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: helm-task
    meta.helm.sh/release-namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
  storageClassName: gp2
